run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - typecheck

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy for this codebase
      - shadow          # Shadow declarations are common in Go and usually harmless
  staticcheck:
    checks: ["all", "-SA1019"]  # Ignore deprecation warnings for now

issues:
  exclude-rules:
    # Test files can have unchecked errors and unused writes
    - path: _test\.go
      linters:
        - errcheck
        - govet
    # Test utilities can have unchecked errors
    - path: testutil/
      linters:
        - errcheck
    # Allow unused parameters in interface implementations
    - linters:
        - unused
      source: "^func \\(.*\\) [A-Z]"
  max-issues-per-linter: 50
  max-same-issues: 10
