DROP TABLE IF EXISTS findings;
DROP TABLE IF EXISTS scans;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS cloud_credentials;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS organizations;
DROP EXTENSION IF EXISTS "uuid-ossp";
